### ISSUE TITLE
To-Do for MVP

### ISSUE THREAD

**Issue by erlewa** [asfadmin/archive_heatmaps#34]
- [ ] Comprehensive list of data sets imported
 - [ ] Memory optimization in the server code
 - [x] Base colormap scale on the maximum weight
 - [ ] Make a legend for the colormap values
 - [x] Lock zoom and pan to the map, make it smart not just constants
 - [x] Styling pass for leptos UI
 - [x] Export to png button
 - [ ] Code cleanup!!!
 - [ ] Create some documentation
 - [ ] Add a coordinate grid overlay
 - [ ] Break the request for World Outline data out into its own request so we only fetch it once
 - [x] Fix the services CORS policy, currently permissive, needs proper handling
